#!/bin/bash -e
#
# Run all tests

cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

FORMATTABLE="authsrv chord connector match/datanode match/indexnode sdk dispatcher dynamicmq"

FMT=$FORMATTABLE


echo "Running tests..."
cd $cur/connector
go test -v
cd $cur/chord
go test -v
cd $cur/match/datanode
go test -v
cd $cur/match/indexnode
go test -v


echo "Checking gofmt..."
cd $cur
fmtRes=$(gofmt -l $FMT)
if [ -n "${fmtRes}" ]; then
    echo -e "gofmt checking failed:\n${fmtRes}"
    exit 255
fi


echo "Success"
